Automatically publish a release and upload to NuGet when tag is created

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -249,3 +249,45 @@ jobs:
         dotnet add csharp.test package ParquetSharp -v ${{ steps.get-version.outputs.version }}
     - name: Build & Run .NET unit tests
       run: dotnet test csharp.test --configuration=Release --framework ${{ steps.dotnet.outputs.framework }}
+    outputs:
+      version: ${{ steps.get-version.outputs.version }}
+
+  # Create a GitHub release and publish the NuGet packages to nuget.org when a tag is pushed.
+  publish-release:
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !github.event.repository.fork
+    name: Publish release
+    runs-on: ubuntu-latest
+    needs: test-nuget
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Check version
+      id: check-version
+      shell: pwsh
+      run: |
+        $version = (Select-Xml -Path ./csharp/ParquetSharp.csproj -XPath '/Project/PropertyGroup/Version/text()').node.Value
+        $tag = "${{ github.ref }}".SubString(10)
+        if (-not ($tag -eq $version)) {
+          echo "::error ::There is a mismatch between the project version ($version) and the tag ($tag)"
+          exit 1
+        }
+        echo "::set-output name=version::$version"
+    - name: Download NuGet artifact
+      uses: actions/download-artifact@v2
+      with:
+        name: nuget-package
+        path: nuget
+    # if version contains "-" treat it as pre-release
+    # example: 1.0.0-beta1
+    - name: Create release
+      uses: softprops/action-gh-release@v1
+      with:
+        name: ParquetSharp ${{ steps.check-version.outputs.version }}
+        draft: true
+        prerelease: ${{ contains(steps.check-version.outputs.version, '-') }}
+        files: |
+          nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Publish to NuGet
+      run: dotnet nuget push nuget/ParquetSharp.${{ steps.check-version.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
